spring:
  application:
    name: zuul-api-gateway
  
server:
  port: 8080
  
zuul:
  routes:
    emp-api:
      url: http://localhost:8081
    say-hello:
      url: http://localhost:8082
      
  ribbon:
    eureka:
      enabled: false