spring:
  h2:
    console:
      enabled: true
      path: /h2
   
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  
  jpa:
    show-sql: true 
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
server:
  port: 8080
