spring:
  application:
    name: spring-cloud-ribbon
 
server:
  port: 8888
 
ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000