spring:
  mail:
    host: linuxservice.oneshield.com
    port: 25
    username: phsharma
    password: oneshield4
    
    properties:
      mail:
        smtp:
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: false